/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import * as THREE from 'three'


export default function Model({ ...props }) {
  const group = useRef()
  const scroll = useScroll()
  const { width, height } = useThree((state) => state.viewport)

  const { nodes, materials } = useGLTF('/logo.glb')
  const rsqw = (t, delta = 0.1, a = 1, f = 1 / (2 * Math.PI)) => (a / Math.atan(1 / delta)) * Math.atan(Math.sin(2 * Math.PI * t * f) / delta)

  // group.current.position.z = 10;

  // useFrame((state, delta) => {
  //   const r1 = scroll.range(0 / 4, 1 / 4);
  //   const r2 = scroll.range(1 / 4, 1 / 4);
  //   const r3 = scroll.visible(4 / 5, 1 / 5);
  //   // group.current.rotation
  //   // group.current.rotation.x = Math.PI - (Math.PI / 2) * rsqw(r1) + r2 * 0.33;
  //   // mbp16.current.rotation.x = Math.PI - (Math.PI / 2) * rsqw(r1) + r2 * 0.33
  //   // mbp14.current.rotation.x = Math.PI - (Math.PI / 2) * rsqw(r1) - r2 * 0.39
  //   group.current.rotation.y = THREE.MathUtils.damp(group.current.rotation.y, (-Math.PI / 1.45) * r2, 4, delta)
  //   // group.current.position.x = THREE.MathUtils.damp(group.current.position.x, (-width / 7) * r2, 4, delta)
  //   // group.current.scale.x = group.current.scale.y = group.current.scale.z = THREE.MathUtils.damp(group.current.scale.z, 1 + 0.24 * (1 - rsqw(r1)), 4, delta)
  //   // keyLight.current.position.set(0.25 + -15 * (1 - r1), 4 + 11 * (1 - r1), 3 + 2 * (1 - r1))
  //   // left.current.classList.toggle('show', r3)
  //   // right.current.classList.toggle('show', r3)
  // })



  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.left.geometry} material={materials['Material.001']} position={[-0.11, 0, 0.08]} scale={[20.8, 367.51, 20.76]} material-color="#c84dd1" />
      <mesh geometry={nodes.right.geometry} material={materials['Material.002']} position={[0.22, 0, -0.14]} rotation={[0, Math.PI / 2, 0]} scale={[-20.76, 367.51, 20.8]} material-color="#c84dd1" />
    </group>
  )
}

useGLTF.preload('/logo.glb')
