/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/logoc.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.left.geometry} material={materials['Material.001']} position={[-0.11, 0, 0.08]} scale={[20.8, 367.51, 20.76]} />
      <mesh geometry={nodes.right.geometry} material={materials['Material.002']} position={[0.22, 0, -0.14]} rotation={[0, Math.PI / 2, 0]} scale={[-20.76, 367.51, 20.8]} />
    </group>
  )
}

useGLTF.preload('/logoc.glb')
